// <auto-generated />
namespace TableTennisTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SecondAttemptGlobalStats : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SecondAttemptGlobalStats));
        
        string IMigrationMetadata.Id
        {
            get { return "201703301459310_Second-Attempt-GlobalStats"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
