// <auto-generated />
namespace TableTennisTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201704031704436_Add-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
